Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,17 +18,27 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
         run: |
-          aws s3 cp s3://ver-bucket-test/version.txt
+          aws s3 cp s3://ver-bucket-test/version.txt .
 
       - name: Read Current Version
         id: read_version
-        run: echo "::set-output name=version::$(cat version.txt)"
+        run: |
+          if [ -f version.txt ]; then
+            echo "::set-output name=version::$(cat version.txt)"
+          else
+            echo "::error::Failed to read version.txt"
+            exit 1
+          fi
 
       - name: Increment Version
         id: increment_version
-        run: echo "::set-output name=version::$(node -e "console.log((process.env.INPUT_VERSION.split('.').map(Number).join('.') + 1).replace(/\.0/g, '.'))")"
-        env:
-          INPUT_VERSION: ${{ steps.read_version.outputs.version }}
+        run: |
+          if [ -n "${{ steps.read_version.outputs.version }}" ]; then
+            echo "::set-output name=version::$(node -e "console.log((process.env.INPUT_VERSION.split('.').map(Number).join('.') + 1).replace(/\.0/g, '.'))")"
+          else
+            echo "::error::Failed to get the current version from read_version step"
+            exit 1
+          fi
 
       - name: Write New Version
         run: echo "${{ steps.increment_version.outputs.version }}" > version.txt
